# Generated by Django 3.2.4 on 2021-06-09 12:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('talent', models.CharField(blank=True, max_length=30)),
                ('medical_records', models.FileField(blank=True, upload_to='medical')),
                ('school_report', models.FileField(blank=True, upload_to='school')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
