# Generated by Django 3.2.4 on 2021-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='medical_records',
            field=models.FileField(blank=True, upload_to='static/medical'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school_report',
            field=models.FileField(blank=True, upload_to='static/school'),
        ),
    ]
