# Generated by Django 3.2.4 on 2021-06-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_auto_20210609_1601'),
        ('child', '0002_auto_20210609_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopter.adopter'),
        ),
    ]
