# Generated by Django 3.2.4 on 2021-06-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponser', '0001_initial'),
        ('child', '0003_child_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sponser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponser.sponser'),
        ),
    ]
