# Generated by Django 3.2.4 on 2021-06-09 13:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
